-- 05_rfm_segmentation.sql
-- Purpose: Segment customers using RFM metrics.
--
-- RFM definitions:
-- Recency   : Days since the customer's latest purchase.
-- Frequency : Number of distinct purchase invoices.
-- Monetary  : Total revenue generated by the customer.
--
-- Note:
-- CustomerID is required for customer-level segmentation.
-- Transactions without CustomerID are excluded from this analysis.

WITH cleaned_data AS (
    SELECT
        InvoiceNo,
        DATE(TIMESTAMP(InvoiceDate)) AS order_date,
        CustomerID,
        Quantity * UnitPrice AS Revenue
    FROM `ecommerce_data`
    WHERE
        InvoiceNo NOT LIKE 'C%'
        AND LENGTH(StockCode) >= 5
        AND Quantity > 0
        AND UnitPrice > 0
        AND Quantity NOT IN (80995, 74215)
        AND CustomerID IS NOT NULL
),

base_date AS (
    SELECT
        DATE_ADD(MAX(order_date), INTERVAL 1 DAY) AS analysis_date
    FROM cleaned_data
),

rfm_base AS (
    SELECT
        c.CustomerID,
        DATE_DIFF(b.analysis_date, MAX(c.order_date), DAY) AS recency_days,
        COUNT(DISTINCT c.InvoiceNo) AS frequency,
        ROUND(SUM(c.Revenue), 2) AS monetary
    FROM cleaned_data c
    CROSS JOIN base_date b
    GROUP BY
        c.CustomerID,
        b.analysis_date
),

rfm_score AS (
    SELECT
        CustomerID,
        recency_days,
        frequency,
        monetary,
        NTILE(5) OVER (ORDER BY recency_days DESC) AS r_score,
        NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
        NTILE(5) OVER (ORDER BY monetary ASC) AS m_score
    FROM rfm_base
),

rfm_segment AS (
    SELECT
        *,
        CONCAT(
            CAST(r_score AS STRING),
            CAST(f_score AS STRING),
            CAST(m_score AS STRING)
        ) AS rfm_score,
        r_score + f_score + m_score AS total_rfm_score,
        CASE
            WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4
                THEN 'VIP 고객'
            WHEN r_score >= 4 AND f_score <= 2
                THEN '신규/최근 유입 고객'
            WHEN r_score <= 2 AND f_score >= 4 AND m_score >= 4
                THEN '이탈 위험 우수 고객'
            WHEN r_score <= 2 AND f_score <= 2
                THEN '저활성 고객'
            WHEN f_score >= 4 AND m_score >= 3
                THEN '충성 고객'
            WHEN m_score >= 4
                THEN '고액 구매 고객'
            ELSE '일반 고객'
        END AS customer_segment
    FROM rfm_score
)

SELECT
    customer_segment,
    COUNT(DISTINCT CustomerID) AS customer_count,
    ROUND(AVG(recency_days), 1) AS avg_recency_days,
    ROUND(AVG(frequency), 1) AS avg_frequency,
    ROUND(AVG(monetary), 2) AS avg_monetary,
    ROUND(SUM(monetary), 2) AS total_revenue,
    ROUND(SUM(monetary) / SUM(SUM(monetary)) OVER () * 100, 2) AS revenue_share_pct
FROM rfm_segment
GROUP BY customer_segment
ORDER BY total_revenue DESC;
